# Generated by Django 5.1.4 on 2024-12-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_document_remove_record_category_delete_contest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='school',
        ),
    ]
