# Generated by Django 5.1.4 on 2024-12-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_record_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Школа'),
        ),
    ]
