# Generated by Django 5.1.4 on 2024-12-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_school_remove_record_school_custmouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmouser',
            name='fio',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='custmouser',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teachers.school', verbose_name='Школа'),
        ),
    ]
