# Generated by Django 5.1.4 on 2025-01-26 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
