# Generated by Django 5.1.4 on 2025-01-27 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_document_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='records_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='teachers.record', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='review',
            name='records_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teachers.record', verbose_name='Публикация'),
        ),
    ]
