# Generated by Django 5.1.4 on 2025-01-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_alter_feedback_moderator_alter_feedback_records_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='records_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='teachers.record', verbose_name='Публикация'),
        ),
    ]
